language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: RKo8OQ35yaSW+IMgwz1wHmYgKaPN+RDN8IgR1qwCAUPfFkS3tmNj0fAFEsX66VWJtENNIM3NsNpyh+crD8bgwygYq81SFcbCIPQFbjj2QVCLRlCtaJ/LCkcYKroLki27GMaZLXGfhhmUI4XGqkmS82wdAgfN96MHNPsGW07+l+S7crjp70mmr9ZasF5QvLNJKbCnPIhtWJuD0wvHr6QPqXplqqyRp1D1w3q/I8lgss/ZeI6r6wuprE9KfwZG30jdu+5ErUMgE3+hUVcavbe4iRFCcvWOsIeyVijpJgCho2R54lwn0ich6BvcDl1tPQYSz+nrTE7q0U7xxWvHMSC2/FoghWtQWpyTLqjajP+vxU0G+mKf+QS0uup7gy1MjDwZo5D63eH4ld+LjhpvHdlx9ZjwrdlLRamuwbKglxkARjfafQ8LYjRI5N8V4OMzz4f1bFoOLgCxCzxcsg2sU+71dScYyhdh5qNeRmf50yyqXHg2KCIeTOCLXFnnhGzL7MofMii8YERo9c+ewCF42YTge4CpJjveRSQ4/nvdXLo5FVqH74e9ulGrihQtotQkrUMVPkUO51/dk0HRA5GpZNCT66hmIPU9mpglN3SGbwhwz8FsODYyEsC2ZaBTkSKGlxd6cWiGWKUGDqw43HXe73H+2fm2P5X/618gF98I6Uh5CSE=
